name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank s for your first issue in woodelivery'' first issue'
        pr-message: 'Thank s for your first pull request in woodelivery'' first pr'
